version: "3"
services:
    nginx:
        restart: always
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./:/code
            - ./Docker/NGINX/default.conf:/etc/nginx/conf.d/default.conf

    php:
        restart: always
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./:/code
            - ./Docker/PHP/php.ini:/usr/local/etc/php/php.ini

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always
        volumes:
            - ./Docker/MYSQL/database:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./Docker/PHP/php.ini:/usr/local/etc/php/php.ini